exclude: |
  ^data/|requirements/requirements_linux\.in$|requirements/requirements_windows\.in$|README\.md$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
        args:
          - --pytest-test-first
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
      - id: requirements-txt-fixer
        args:
          - requirements/requirements_linux.in
          - requirements/requirements_windows.in
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          [
            --multi-line=3,
            --trailing-comma,
            --force-grid-wrap=0,
            --use-parentheses,
            --profile=black,
          ]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black


  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff
        args:
          - --fix

  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5